# Generated by Django 5.1.4 on 2025-01-11 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
